# Generated by Django 5.2.1 on 2025-05-12 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserLogin', '0002_otpmodel_usermodel_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='address',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='city',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='pic',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='state',
        ),
    ]
