# Generated by Django 5.1.5 on 2025-01-31 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('Category', models.CharField(max_length=100)),
                ('Description', models.TextField(max_length=500)),
                ('Content', models.TextField(blank=True)),
                ('Poster', models.ImageField(upload_to='images/')),
                ('Tags', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
