# Generated by Django 5.1.5 on 2025-01-31 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0002_remove_post_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Poster',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
