# Generated by Django 5.1.5 on 2025-01-31 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0003_post_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Tags',
        ),
    ]
