# Generated by Django 5.1.5 on 2025-02-01 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0005_post_rentprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('tractors', 'Tractors'), ('tools', 'Farm Tools'), ('seeds', 'Seeds'), ('fertilizers', 'Fertilizers')], default='tractors', max_length=50),
        ),
    ]
