# Generated by Django 5.1.5 on 2025-02-12 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0006_post_category'),
        ('UserLogin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='UserLogin.user'),
            preserve_default=False,
        ),
    ]
