# Generated by Django 5.2.1 on 2025-05-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostsView', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='price',
            field=models.IntegerField(),
        ),
    ]
