# Generated by Django 5.2.1 on 2025-05-12 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PostsView', '0002_alter_postmodel_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postmodel',
            old_name='description',
            new_name='Description',
        ),
    ]
